version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://your_db_user:your_db_password@postgres/your_db_name"
    ports:
      - "8000:8000"
    depends_on:
      - postgres


volumes:
  pg_data:
